### PR TITLE
Add fresh new tsconfig

### PR DESCRIPTION
**Pull request by jeremybarbet**
@birkir Alright alright, fresh new tsconfig is here. I just open a PR because the tsconfig.json is a bit different from the npm package than the one you were using here. So if you can take a look at it, and make sure everything is good like you want we can merge. So far running `yarn lint` works 👌🏻

cf: https://github.com/ueno-llc/styleguide/blob/master/packages/tslint-config/tsconfig-react.json

### CODE REVIEW

**Comment by birkir** [comment]
Great 👍🏻 

I think we have to create two tslint as this one is way to strict for web projects. I know our developers want to take it easy on many marketing site projects. We (especially me) may have gone overboard when we were designing the tslint.

@ueno/tslint:recommended
@ueno/tslint:basic

What do you think 🤔

**Comment by birkir** [comment]
I am also skeptical about pulling ts compiler options that have to be different for each setup (next/gatsby/cra) from node modules

**Comment by jeremybarbet** [comment]
#### About `tslint`

Yeah, we could have a differents setup. One basic and one advanced. But if the basic one is enable by default through `create-ueno-app` or `react-native-starter` then when would we use the advanced one?

I would be more agree to find a middle ground not too strict noo too simple and that everybody can be happy with.

#### About `tsconfig`

Yeah I was thinking about it while updating cra and the tsconfig isn't the same, so maybe not a so good idea. Unless we create 3 different tsconfig for cra/next/gatsby. In this case it means, if we create a new project with one of them without `create-ueno-app` will the config work? If yes, then we could do that, if not, probably better to keep the config unique for each project.

**Comment by birkir** [comment]
Agreed!

**Pull request merged**
